### ISSUE TITLE
Like sqlkata?

### ISSUE THREAD

**Issue by hsorbo** [vivainio/Fapper#2]
> Why Fapper when there are millions of other SQL generators on the web?
> There aren't for .NET. Search for yourself.

Are you aware of sqlkata?
Perhaps its worth mentioning as a C# alternative?

https://sqlkata.com/docs

**Comment by vivainio** [comment]
I was not aware about it, thanks. It's pretty much what "Fapper for C#" would look like indeed :). I'll mention it
