### ISSUE TITLE
Library Name Change

### ISSUE THREAD

**Issue by HoraceGonzalez** [vivainio/Fapper#3]
Love the idea! This is definitely something community needs. The name, though is unfortunate because despite best intentions, it may not pass the HR "sniff test", which will undoubtedly hurt adoption.

Looking forward to giving this a test drive!

**Comment by HoraceGonzalez** [comment]
What about FASTSql (F# AST for SQL)?

**Comment by vivainio** [comment]
There is already https://www.nuget.org/packages/FastSql/

**Comment by vivainio** [comment]
Duplicate of #1
