### ISSUE TITLE
Recommend name change

### ISSUE THREAD

**Issue by voronoipotato** [vivainio/Fapper#4]
Fapper is NSFW, and this will definitely either lead to adoption issues or a fork over the name. Some American will otherwise get sued for a hostile work environment, or worse actually empower a hostile work environment.

My personal recommendations are Faddish or FDapper. 

Sorry to be no fun, but F# actually gets used at work in some places.

**Comment by jwosty** [comment]
May I suggest a synonym for "dapper", like "debonair"?

**Comment by vivainio** [comment]
@jwosty debonair was suggested also in https://github.com/vivainio/Fapper/issues/1. Yes, I'm considering a name change, TBD as I do some more verification against Oracle etc.

**Comment by vivainio** [comment]
Name changed to SqlFrags
