### ISSUE TITLE
The value of constructor `SelectS` is not defined

### ISSUE THREAD

**Issue by Idrek** [vivainio/Fapper#5]
Documentation shows an example with

`SelectS ["*"]`

but I cannot find it in the source code and my demo does not compile.

How about following function to fix it?
```
let SelectS (columns: seq<string>) : Frag =
    String.concat ", " columns
    |> (+) "select "
    |> Raw
```

**Comment by vivainio** [comment]
Ah, I removed that recently. The recommended replacement is Select
extension method for Table - or just Raw.

I think I'll just update the doc that got out of date. Thanks for the heads
up!
